using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace Nightfall.UnityMvp
{
    public sealed partial class NightfallGame
    {
        private static class UiToken
        {
            public const float Title=44,Heading=28,Button=22,Body=18,Secondary=15,Counter=13;
            public static readonly Color Surface=new Color(.012f,.025f,.035f,.94f),SurfaceSoft=new Color(.018f,.045f,.058f,.88f),Cyan=new Color(.08f,.78f,.92f),Gold=new Color(1,.68f,.20f),Text=new Color(.94f,.97f,1),Muted=new Color(.68f,.76f,.80f);
        }

        private Canvas modernCanvas;private RectTransform safeAreaRoot;private TMP_FontAsset modernFont;private Sprite panelSprite,buttonSprite,barSprite,panelArtSprite,cardArtSprite,buttonArtSprite;
        private GameObject menuScreen,heroScreen,hudScreen,upgradeScreen,petScreen,pauseScreen,endScreen;
        private TMP_Text timerText,killsText,heroNameText,hpText,xpText,levelText,petHudText,bossNameText,endTitleText,endStatsText,abilityNoticeText;
        private Image hpFill,xpFill,petHudPortrait,bossFill,abilityNoticeIcon;private RectTransform bossRoot,loadoutRoot,upgradeCardsRoot,petModalContent,abilityNoticeRoot,joystickBase,joystickKnob;
        private Button pauseButton;private State uiRenderedState=(State)(-1);private int uiRenderedLevel=-1,uiRenderedPetCount=-1;private Enemy uiRenderedBoss;

        private void BuildModernUi()
        {
            modernFont=TMP_FontAsset.CreateFontAsset(uiFont);modernFont.atlasPopulationMode=AtlasPopulationMode.Dynamic;
            panelSprite=CreateNineSlice("UiPanel",new Color(.025f,.075f,.09f,1),new Color(.10f,.68f,.78f,1));buttonSprite=CreateNineSlice("UiButton",new Color(.04f,.12f,.15f,1),new Color(.18f,.82f,.92f,1));barSprite=CreateNineSlice("UiBar",new Color(.018f,.035f,.045f,1),new Color(.12f,.32f,.38f,1));
            panelArtSprite=TextureSprite(uiPanelFrame);cardArtSprite=TextureSprite(uiCardFrame);buttonArtSprite=TextureSprite(uiButtonPlate);
            var canvasGo=new GameObject("NightfallCanvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));modernCanvas=canvasGo.GetComponent<Canvas>();modernCanvas.renderMode=RenderMode.ScreenSpaceOverlay;modernCanvas.sortingOrder=100;
            var scaler=canvasGo.GetComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1920,1080);scaler.screenMatchMode=CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;scaler.matchWidthOrHeight=.5f;
            if(FindAnyObjectByType<EventSystem>()==null)new GameObject("EventSystem",typeof(EventSystem),typeof(StandaloneInputModule));
            safeAreaRoot=Rect("SafeAreaRoot",canvasGo.transform);Stretch(safeAreaRoot,0,0,0,0);safeAreaRoot.gameObject.AddComponent<SafeAreaLayout>();
            menuScreen=BuildMenu();heroScreen=BuildHeroSelection();hudScreen=BuildHud();upgradeScreen=BuildUpgradeScreen();petScreen=BuildPetScreen();pauseScreen=BuildPauseScreen();endScreen=BuildEndScreen();
            SyncModernUi(true);
        }

        private GameObject BuildMenu()
        {
            var root=ScreenRoot("MenuScreen",true);AddBackground(root.transform);var panel=Panel("MenuPanel",root.transform,new Vector2(820,620));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,new Vector2(0,0));var stack=Vertical("Content",panel,32,22,TextAnchor.MiddleCenter);Stretch(stack,70,70,70,70);
            LayoutText(stack,"BUREAU BREAKERS",UiToken.Title,30,44,72,FontStyles.Bold);LayoutText(stack,"CHAPTER 1",UiToken.Heading,20,28,46,FontStyles.Bold,UiToken.Gold);LayoutText(stack,"МАГИЯ ПОД НАДЗОРОМ",UiToken.Secondary,13,17,36);Spacer(stack,24);PrimaryButton(stack,"ИГРАТЬ",()=>SetUiState(State.HeroSelect),300,76);Spacer(stack,12);LayoutText(stack,"URBAN FANTASY SURVIVAL",UiToken.Secondary,12,15,32,FontStyles.Normal,UiToken.Cyan);return root;
        }

        private GameObject BuildHeroSelection()
        {
            var root=ScreenRoot("HeroSelection",true);AddBackground(root.transform);var title=Text("Title",root.transform,"ВЫБЕРИТЕ ОПЕРАТИВНИКА",UiToken.Title,30,44,TextAlignmentOptions.Center);SetAnchored(title.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-48),new Vector2(1000,70));
            var subtitle=Text("Subtitle",root.transform,"Три боевых протокола. Один шанс пережить ночь.",UiToken.Secondary,12,15,TextAlignmentOptions.Center);SetAnchored(subtitle.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-112),new Vector2(900,38));
            var row=Horizontal("CharacterCards",root.transform,42,0,TextAnchor.MiddleCenter);SetAnchored(row,new Vector2(.5f,.5f),new Vector2(.5f,.5f),new Vector2(0,-24),new Vector2(1660,790));
            for(int i=0;i<3;i++){HeroKind kind=(HeroKind)i;BuildCharacterCard(row,kind);}return root;
        }

        private void BuildCharacterCard(RectTransform row,HeroKind kind)
        {
            var d=GameCatalog.Hero(kind);var card=Panel("Character_"+kind,row,new Vector2(500,760));var le=card.gameObject.AddComponent<LayoutElement>();le.preferredWidth=500;le.preferredHeight=760;var stack=Vertical("Content",card,20,12,TextAnchor.UpperCenter);Stretch(stack,34,34,34,34);
            var portraitBox=Panel("PortraitArea",stack,new Vector2(420,275),UiToken.SurfaceSoft);portraitBox.gameObject.AddComponent<LayoutElement>().preferredHeight=275;var portrait=ImageNode("Portrait",portraitBox,heroPortraits[(int)kind],true);Stretch(portrait.rectTransform,42,42,20,20);
            LayoutText(stack,d.displayName,UiToken.Heading,20,28,42,FontStyles.Bold,kind==HeroKind.Amelia?UiToken.Gold:kind==HeroKind.Sam?new Color(.95f,.20f,.30f):UiToken.Cyan);
            LayoutText(stack,d.subtitle+"   •   "+d.hp.ToString("0")+" HP",UiToken.Secondary,12,15,35);
            LayoutText(stack,HeroAbilitiesCardSummary(kind),UiToken.Body,13,17,235,FontStyles.Normal,UiToken.Text,TextAlignmentOptions.TopLeft);
            Spacer(stack,8);PrimaryButton(stack,"В БОЙ",()=>{SetHero(kind);StartRun();},310,66);
        }

        private GameObject BuildHud()
        {
            var root=ScreenRoot("GameplayHUD",false);
            var heroPanel=Panel("HeroHUD",root.transform,new Vector2(590,174));SetAnchored(heroPanel,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-22),heroPanel.sizeDelta);
            var row=Horizontal("HeroContent",heroPanel,18,0,TextAnchor.MiddleLeft);Stretch(row,24,24,20,20);var portrait=ImageNode("HeroPortrait",row,null,true);portrait.rectTransform.sizeDelta=new Vector2(108,108);portrait.gameObject.AddComponent<LayoutElement>().preferredWidth=108;
            var stats=Vertical("Stats",row,7,5,TextAnchor.MiddleLeft);stats.gameObject.AddComponent<LayoutElement>().preferredWidth=300;heroNameText=LayoutText(stats,"ГЕРОЙ",UiToken.Heading,20,27,34,FontStyles.Bold);levelText=LayoutText(stats,"LV 1",UiToken.Secondary,12,15,22);hpFill=Bar(stats,"HPBar",new Color(.82f,.12f,.18f),300,30);hpText=Text("HPValue",hpFill.transform.parent,"HP",UiToken.Secondary,13,16,TextAlignmentOptions.Center);Stretch(hpText.rectTransform,8,8,2,2);hpText.fontStyle=FontStyles.Bold;xpFill=Bar(stats,"XPBar",new Color(.10f,.80f,.92f),300,24);xpText=Text("XPValue",xpFill.transform.parent,"XP",UiToken.Counter,11,14,TextAlignmentOptions.Center);Stretch(xpText.rectTransform,8,8,2,2);xpText.fontStyle=FontStyles.Bold;
            var pet=Vertical("Pet",row,6,3,TextAnchor.MiddleCenter);pet.gameObject.AddComponent<LayoutElement>().preferredWidth=110;petHudPortrait=ImageNode("PetPortrait",pet,null,true);petHudPortrait.rectTransform.sizeDelta=new Vector2(72,72);petHudText=LayoutText(pet,"0 / 3",UiToken.Counter,11,13,34);
            timerText=Text("Timer",root.transform,"00:00",UiToken.Heading,22,28,TextAlignmentOptions.Center);SetAnchored(timerText.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-30),new Vector2(240,54));killsText=Text("Kills",root.transform,"УНИЧТОЖЕНО: 0",UiToken.Body,14,18,TextAlignmentOptions.Right);SetAnchored(killsText.rectTransform,new Vector2(1,1),new Vector2(1,1),new Vector2(-210,-32),new Vector2(330,44));
            pauseButton=PrimaryButton(root.transform,"ПАУЗА",()=>SetUiState(State.Paused),180,58);SetAnchored((RectTransform)pauseButton.transform,new Vector2(1,1),new Vector2(1,1),new Vector2(-24,-24),new Vector2(180,58));
            var qa=Horizontal("QaTools",root.transform,12,0,TextAnchor.MiddleLeft);SetAnchored(qa,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-214),new Vector2(650,56));PrimaryButton(qa,"QA GOD",()=>qaInvulnerable=!qaInvulnerable,180,52);PrimaryButton(qa,"QA +1 LEVEL",QaLevelUp,205,52);PrimaryButton(qa,"QA PET",QaUnlockPet,180,52);
            bossRoot=Panel("BossHUD",root.transform,new Vector2(760,92));SetAnchored(bossRoot,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-102),bossRoot.sizeDelta);bossNameText=Text("BossName",bossRoot,"БОСС",UiToken.Body,14,18,TextAlignmentOptions.Center);SetAnchored(bossNameText.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-16),new Vector2(660,28));bossFill=Bar(bossRoot,"BossBar",new Color(.85f,.08f,.12f),660,20);SetAnchored(bossFill.transform.parent as RectTransform,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,18),new Vector2(660,20));
            loadoutRoot=Vertical("Loadout",root.transform,8,8,TextAnchor.LowerRight);SetAnchored(loadoutRoot,new Vector2(1,0),new Vector2(1,0),new Vector2(-24,24),new Vector2(460,320));
            abilityNoticeText=Text("AbilityNotice",root.transform,"",UiToken.Secondary,12,15,TextAlignmentOptions.Left);abilityNoticeRoot=Panel("AbilityNoticePanel",root.transform,new Vector2(430,72));SetAnchored(abilityNoticeRoot,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-205),abilityNoticeRoot.sizeDelta);abilityNoticeIcon=ImageNode("Icon",abilityNoticeRoot,null,true);SetAnchored(abilityNoticeIcon.rectTransform,new Vector2(0,.5f),new Vector2(0,.5f),new Vector2(16,0),new Vector2(48,48));abilityNoticeText.transform.SetParent(abilityNoticeRoot,false);SetAnchored(abilityNoticeText.rectTransform,new Vector2(0,0),new Vector2(1,1),Vector2.zero,Vector2.zero);abilityNoticeText.rectTransform.offsetMin=new Vector2(78,10);abilityNoticeText.rectTransform.offsetMax=new Vector2(-14,-10);abilityNoticeRoot.gameObject.SetActive(false);
            joystickBase=Panel("TouchJoystick",root.transform,new Vector2(150,150),new Color(.02f,.08f,.10f,.55f));joystickBase.pivot=Vector2.one*.5f;joystickBase.gameObject.SetActive(false);joystickKnob=Panel("Knob",joystickBase,new Vector2(64,64),new Color(.10f,.75f,.88f,.75f));Anchor(joystickKnob,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);
            return root;
        }

        private GameObject BuildUpgradeScreen(){var root=ScreenRoot("UpgradeScreen",false,true);var panel=Panel("UpgradePanel",root.transform,new Vector2(1500,760));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);LayoutText(Vertical("Header",panel,0,0,TextAnchor.UpperCenter),"НОВЫЙ УРОВЕНЬ",UiToken.Title,30,44,68,FontStyles.Bold);upgradeCardsRoot=Horizontal("Cards",panel,34,0,TextAnchor.MiddleCenter);SetAnchored(upgradeCardsRoot,new Vector2(.5f,.5f),new Vector2(.5f,.5f),new Vector2(0,-35),new Vector2(1330,560));return root;}
        private GameObject BuildPetScreen(){var root=ScreenRoot("PetScreen",false,true);petModalContent=Panel("PetModal",root.transform,new Vector2(1050,680));Anchor(petModalContent,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);return root;}
        private GameObject BuildPauseScreen(){var root=ScreenRoot("PauseScreen",false,true);var panel=Panel("PausePanel",root.transform,new Vector2(650,760));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);var stack=Vertical("Content",panel,28,14,TextAnchor.MiddleCenter);Stretch(stack,75,75,55,55);LayoutText(stack,"ПАУЗА",UiToken.Title,30,44,80,FontStyles.Bold);PrimaryButton(stack,"ПРОДОЛЖИТЬ",()=>SetUiState(State.Playing),360,64);PrimaryButton(stack,"QA GOD",()=>qaInvulnerable=!qaInvulnerable,360,58);PrimaryButton(stack,"QA +1 LEVEL",QaLevelUp,360,58);PrimaryButton(stack,"QA PET",QaUnlockPet,360,58);PrimaryButton(stack,"НАЧАТЬ ЗАНОВО",StartRun,360,64);PrimaryButton(stack,"ВЫБОР ГЕРОЯ",()=>{player.SetActive(false);SetUiState(State.HeroSelect);},360,64);return root;}
        private GameObject BuildEndScreen(){var root=ScreenRoot("EndScreen",false,true);var panel=Panel("EndPanel",root.transform,new Vector2(820,520));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);var stack=Vertical("Content",panel,28,18,TextAnchor.MiddleCenter);Stretch(stack,70,70,60,60);endTitleText=LayoutText(stack,"ЗАБЕГ ЗАВЕРШЁН",UiToken.Title,28,44,90,FontStyles.Bold);endStatsText=LayoutText(stack,"Уничтожено: 0",UiToken.Heading,18,28,60);PrimaryButton(stack,"ЕЩЁ РАЗ",()=>SetUiState(State.HeroSelect),320,72);return root;}

        private void SyncModernUi(bool force=false)
        {
            if(modernCanvas==null)return;Rect safe=Screen.safeArea;safeAreaRoot.anchorMin=new Vector2(safe.xMin/Screen.width,safe.yMin/Screen.height);safeAreaRoot.anchorMax=new Vector2(safe.xMax/Screen.width,safe.yMax/Screen.height);
            if(force||uiRenderedState!=state){uiRenderedState=state;menuScreen.SetActive(state==State.Menu);heroScreen.SetActive(state==State.HeroSelect);hudScreen.SetActive(state==State.Playing);upgradeScreen.SetActive(state==State.Upgrade);petScreen.SetActive(state==State.PetUnlock);pauseScreen.SetActive(state==State.Paused);endScreen.SetActive(state==State.Dead||state==State.Victory);if(state==State.Upgrade)RenderUpgradeCards();if(state==State.PetUnlock)RenderPetModal();if(state==State.Dead||state==State.Victory){endTitleText.text=state==State.Victory?"ЗАБЕГ ЗАВЕРШЁН":"ОПЕРАТИВНИК ПОГИБ";endStatsText.text="Уничтожено целей: "+kills;}}
            if(state!=State.Playing)return;heroNameText.text=hero.displayName;levelText.text="УРОВЕНЬ "+level;hpText.text="HP  "+Mathf.CeilToInt(hp)+" / "+Mathf.CeilToInt(maxHp);hpFill.fillAmount=maxHp>0?hp/maxHp:0;xpText.text="ОПЫТ  "+xp+" / "+xpNeed;xpFill.fillAmount=xpNeed>0?(float)xp/xpNeed:0;timerText.text=$"{(int)(runTime/60):00}:{(int)(runTime%60):00}";killsText.text="УНИЧТОЖЕНО: "+kills;
            var heroPortrait=hudScreen.transform.Find("HeroHUD/HeroContent/HeroPortrait")?.GetComponent<Image>();if(heroPortrait!=null)heroPortrait.sprite=TextureSprite(heroPortraits[(int)hero.kind]);petHudPortrait.gameObject.SetActive(petUnlocked);petHudPortrait.sprite=petUnlocked?TextureSprite(petPortrait):null;petHudText.text=petUnlocked?petDefinition.displayName:"ВКУСНЯШКИ\n"+treatsCollected+" / 3";
            bossRoot.gameObject.SetActive(currentBoss!=null);if(currentBoss!=null){bossNameText.text=currentBoss.boss.name;bossFill.fillAmount=currentBoss.maxHp>0?currentBoss.hp/currentBoss.maxHp:0;}
            bool showAbility=abilityFlashTimer>0;abilityNoticeRoot.gameObject.SetActive(showAbility);if(showAbility){abilityNoticeText.text=abilityFlash;abilityNoticeIcon.sprite=abilityFlashSlot>=0?TextureSprite(UiIcon(AbilityIconId(hero.kind,abilityFlashSlot))):null;}
            bool showJoystick=joystickFinger>=0;joystickBase.gameObject.SetActive(showJoystick);if(showJoystick){Vector2 screenPos=joystickOrigin;RectTransformUtility.ScreenPointToLocalPointInRectangle(safeAreaRoot,screenPos,modernCanvas.worldCamera,out Vector2 local);joystickBase.anchoredPosition=local;joystickKnob.anchoredPosition=Vector2.ClampMagnitude(moveInput,1)*42f;}
            if(force||uiRenderedLevel!=level||uiRenderedPetCount!=treatsCollected||uiRenderedBoss!=currentBoss){uiRenderedLevel=level;uiRenderedPetCount=treatsCollected;uiRenderedBoss=currentBoss;RenderLoadout();}
        }

        private void RenderUpgradeCards(){Clear(upgradeCardsRoot);for(int i=0;i<3;i++){int index=i;var u=offered[i];if(u==null)continue;var card=Panel("UpgradeCard_"+i,upgradeCardsRoot,new Vector2(410,520));var le=card.gameObject.AddComponent<LayoutElement>();le.preferredWidth=410;le.preferredHeight=520;var stack=Vertical("Content",card,22,13,TextAnchor.UpperCenter);Stretch(stack,30,30,28,28);var icon=ImageNode("Icon",stack,UiIcon(u.icon),true);icon.rectTransform.sizeDelta=new Vector2(96,96);icon.gameObject.AddComponent<LayoutElement>().preferredHeight=96;LayoutText(stack,u.name,UiToken.Heading,18,27,72,FontStyles.Bold);int next=u.ability>=0?abilityRanks[u.ability]+1:0;if(u.ability>=0)LayoutText(stack,next>=6?"ЭВОЛЮЦИЯ":"РАНГ "+next+" / 6",UiToken.Secondary,12,15,28,FontStyles.Bold,UiToken.Gold);LayoutText(stack,u.description,UiToken.Body,14,18,155);Spacer(stack,8);PrimaryButton(stack,"ВЫБРАТЬ",()=>SelectUpgrade(index),270,62);}}
        private void RenderPetModal(){Clear(petModalContent);var stack=Vertical("Content",petModalContent,22,14,TextAnchor.UpperCenter);Stretch(stack,58,58,38,38);LayoutText(stack,"ФАМИЛЬЯР ОТКЛИКНУЛСЯ",UiToken.Title,28,42,62,FontStyles.Bold);var row=Horizontal("PetInfo",stack,34,0,TextAnchor.MiddleCenter);row.gameObject.AddComponent<LayoutElement>().preferredHeight=410;var portrait=Panel("Portrait",row,new Vector2(330,390));portrait.gameObject.AddComponent<LayoutElement>().preferredWidth=330;var image=ImageNode("PetPortrait",portrait,petPortrait,true);Stretch(image.rectTransform,48,48,48,110);var name=Text("Name",portrait,petDefinition.displayName,UiToken.Heading,18,28,TextAlignmentOptions.Center);SetAnchored(name.rectTransform,new Vector2(0,0),new Vector2(1,0),new Vector2(0,34),new Vector2(0,58));var info=Vertical("Description",row,18,12,TextAnchor.MiddleLeft);info.gameObject.AddComponent<LayoutElement>().preferredWidth=510;LayoutText(info,petDefinition.description,UiToken.Body,14,18,150,FontStyles.Normal,UiToken.Text,TextAlignmentOptions.TopLeft);LayoutText(info,"АВТОАТАКА   20% урона героя\nЭХО НАВЫКА   12%\nРОЛЬ   наземный спутник",UiToken.Body,14,18,135,FontStyles.Normal,UiToken.Muted,TextAlignmentOptions.TopLeft);PrimaryButton(stack,"ПРИНЯТЬ ФАМИЛЬЯРА",UnlockPet,360,68);}
        private void RenderLoadout(){Clear(loadoutRoot);int learned=0;for(int i=0;i<5;i++)if(abilityRanks[i]>0)learned++;if(learned==0)return;for(int i=0;i<5;i++){if(abilityRanks[i]<=0)continue;var row=Panel("Ability_"+i,loadoutRoot,new Vector2(430,48),UiToken.SurfaceSoft);row.gameObject.AddComponent<LayoutElement>().preferredHeight=48;var icon=ImageNode("Icon",row,UiIcon(AbilityIconId(hero.kind,i)),true);SetAnchored(icon.rectTransform,new Vector2(0,.5f),new Vector2(0,.5f),new Vector2(8,0),new Vector2(36,36));var label=Text("Label",row,AbilityName(hero.kind,i)+"   РАНГ "+abilityRanks[i],UiToken.Counter,11,13,TextAlignmentOptions.Left);Stretch(label.rectTransform,54,10,7,7);}}
        private void SetUiState(State value){state=value;SyncModernUi(true);}
        public void DebugPreviewUi(string screen)
        {
            if(hero==null)SetHero(HeroKind.Amelia);
            if(screen=="Menu")state=State.Menu;else if(screen=="HeroSelect")state=State.HeroSelect;else if(screen=="HUD"){if(!player.activeSelf)StartRun();state=State.Playing;}else if(screen=="Upgrade"){RollUpgrades();state=State.Upgrade;}else if(screen=="Pet"){petDefinition=PetCatalog.ForOwner(hero.id);petPortrait=Resources.Load<Texture2D>(petDefinition.portraitResource);state=State.PetUnlock;}else if(screen=="Pause")state=State.Paused;else if(screen=="Boss"){if(!player.activeSelf)StartRun();if(currentBoss==null)SpawnBoss(BossKind.EarthDragon);state=State.Playing;}else if(screen=="End")state=State.Victory;SyncModernUi(true);
        }
        public string RunUiLayoutAudit()
        {
            if(modernCanvas==null)return "Canvas is not initialized";int issues=0,labels=0,buttons=0;var safe=safeAreaRoot.rect;
            foreach(var label in modernCanvas.GetComponentsInChildren<TMP_Text>(true)){labels++;if(!label.gameObject.activeInHierarchy)continue;label.ForceMeshUpdate();var rt=label.rectTransform;if(label.preferredWidth>rt.rect.width+1&&!label.enableWordWrapping){Debug.LogWarning("UI_AUDIT horizontal overflow: "+HierarchyPath(rt));issues++;}if(label.preferredHeight>rt.rect.height+1&&label.overflowMode!=TextOverflowModes.Ellipsis){Debug.LogWarning("UI_AUDIT vertical overflow: "+HierarchyPath(rt));issues++;}}
            foreach(var button in modernCanvas.GetComponentsInChildren<Button>(true)){buttons++;if(button.targetGraphic==null){Debug.LogWarning("UI_AUDIT button has no visual: "+HierarchyPath(button.transform));issues++;}}
            string result=$"UI AUDIT: {issues} issue(s), {labels} TMP labels, {buttons} buttons, SafeArea {safe.width:0}x{safe.height:0}";Debug.Log(result);return result;
        }
        private static string HierarchyPath(Transform value){string path=value.name;while(value.parent!=null){value=value.parent;path=value.name+"/"+path;}return path;}

        private GameObject ScreenRoot(string name,bool active,bool dim=false){var go=new GameObject(name,typeof(RectTransform));go.transform.SetParent(safeAreaRoot,false);Stretch((RectTransform)go.transform,0,0,0,0);if(dim){var image=go.AddComponent<Image>();image.color=new Color(0,0,0,.72f);}go.SetActive(active);return go;}
        private void AddBackground(Transform parent){var raw=new GameObject("Background",typeof(RectTransform),typeof(RawImage)).GetComponent<RawImage>();raw.transform.SetParent(parent,false);Stretch(raw.rectTransform,0,0,0,0);raw.texture=uiMenuBackground;raw.uvRect=new Rect(0,0,1,1);raw.color=new Color(.78f,.82f,.86f,1);raw.raycastTarget=false;}
        private RectTransform Panel(string name,Transform parent,Vector2 size,Color? color=null){var rt=Rect(name,parent);rt.sizeDelta=size;var image=rt.gameObject.AddComponent<Image>();bool card=name.StartsWith("Character_")||name.StartsWith("UpgradeCard_");bool large=size.x>=600&&size.y>=400;image.sprite=card&&cardArtSprite!=null?cardArtSprite:large&&panelArtSprite!=null?panelArtSprite:panelSprite;image.type=(card&&cardArtSprite!=null)||(large&&panelArtSprite!=null)?Image.Type.Simple:Image.Type.Sliced;image.color=color??Color.white;return rt;}
        private Button PrimaryButton(Transform parent,string label,Action action,float width,float height){var rt=Rect("Button_"+label,parent);rt.sizeDelta=new Vector2(width,height);var image=rt.gameObject.AddComponent<Image>();image.sprite=buttonArtSprite!=null?buttonArtSprite:buttonSprite;image.type=buttonArtSprite!=null?Image.Type.Simple:Image.Type.Sliced;var button=rt.gameObject.AddComponent<Button>();var colors=button.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1.12f,1.12f,1.12f);colors.pressedColor=new Color(.62f,.78f,.82f);colors.disabledColor=new Color(.25f,.3f,.32f,.7f);colors.fadeDuration=.08f;button.colors=colors;button.onClick.AddListener(()=>action());var text=Text("Label",rt,label,UiToken.Button,17,22,TextAlignmentOptions.Center);Stretch(text.rectTransform,34,34,10,10);text.enableWordWrapping=false;text.overflowMode=TextOverflowModes.Ellipsis;text.fontStyle=FontStyles.Bold;var le=rt.gameObject.AddComponent<LayoutElement>();le.preferredWidth=width;le.preferredHeight=height;le.minHeight=52;return button;}
        private RectTransform Vertical(string name,Transform parent,float padding,float spacing,TextAnchor align){var rt=Rect(name,parent);var layout=rt.gameObject.AddComponent<VerticalLayoutGroup>();layout.padding=new RectOffset((int)padding,(int)padding,(int)padding,(int)padding);layout.spacing=spacing;layout.childAlignment=align;layout.childControlWidth=true;layout.childControlHeight=false;layout.childForceExpandWidth=true;layout.childForceExpandHeight=false;return rt;}
        private RectTransform Horizontal(string name,Transform parent,float spacing,float padding,TextAnchor align){var rt=Rect(name,parent);var layout=rt.gameObject.AddComponent<HorizontalLayoutGroup>();layout.padding=new RectOffset((int)padding,(int)padding,(int)padding,(int)padding);layout.spacing=spacing;layout.childAlignment=align;layout.childControlWidth=false;layout.childControlHeight=false;layout.childForceExpandWidth=false;layout.childForceExpandHeight=false;return rt;}
        private TMP_Text LayoutText(Transform parent,string value,float size,float min,float max,float height,FontStyles style=FontStyles.Normal,Color? color=null,TextAlignmentOptions alignment=TextAlignmentOptions.Center){var text=Text("Text",parent,value,size,min,max,alignment);text.fontStyle=style;text.color=color??UiToken.Text;var le=text.gameObject.AddComponent<LayoutElement>();le.preferredHeight=height;le.minHeight=Mathf.Min(height,28);return text;}
        private TMP_Text Text(string name,Transform parent,string value,float size,float min,float max,TextAlignmentOptions alignment){var rt=Rect(name,parent);var text=rt.gameObject.AddComponent<TextMeshProUGUI>();text.font=modernFont;text.text=value;text.fontSize=size;text.enableAutoSizing=true;text.fontSizeMin=min;text.fontSizeMax=max;text.color=UiToken.Text;text.alignment=alignment;text.enableWordWrapping=true;text.overflowMode=TextOverflowModes.Ellipsis;text.raycastTarget=false;text.margin=new Vector4(2,2,2,2);return text;}
        private Image ImageNode(string name,Transform parent,Texture2D texture,bool preserve){var rt=Rect(name,parent);var image=rt.gameObject.AddComponent<Image>();image.sprite=TextureSprite(texture);image.preserveAspect=preserve;image.raycastTarget=false;return image;}
        private Image Bar(Transform parent,string name,Color fillColor,float width,float height){var bg=Rect(name,parent);bg.sizeDelta=new Vector2(width,height);bg.gameObject.AddComponent<LayoutElement>().preferredHeight=height;var image=bg.gameObject.AddComponent<Image>();image.sprite=barSprite;image.type=Image.Type.Sliced;image.color=Color.white;var fillRt=Rect("Fill",bg);Stretch(fillRt,3,3,3,3);var fill=fillRt.gameObject.AddComponent<Image>();fill.sprite=barSprite;fill.type=Image.Type.Filled;fill.fillMethod=Image.FillMethod.Horizontal;fill.color=fillColor;return fill;}
        private void Spacer(Transform parent,float height){var rt=Rect("Spacer",parent);rt.gameObject.AddComponent<LayoutElement>().preferredHeight=height;}
        private static RectTransform Rect(string name,Transform parent){var go=new GameObject(name,typeof(RectTransform));go.transform.SetParent(parent,false);return (RectTransform)go.transform;}
        private static void Stretch(RectTransform rt,float left,float right,float top,float bottom){rt.anchorMin=Vector2.zero;rt.anchorMax=Vector2.one;rt.offsetMin=new Vector2(left,bottom);rt.offsetMax=new Vector2(-right,-top);}
        private static void Anchor(RectTransform rt,Vector2 min,Vector2 max,Vector2 position){rt.anchorMin=min;rt.anchorMax=max;rt.pivot=(min+max)*.5f;rt.anchoredPosition=position;}
        private static void SetAnchored(RectTransform rt,Vector2 min,Vector2 max,Vector2 position,Vector2 size){rt.anchorMin=min;rt.anchorMax=max;rt.pivot=(min+max)*.5f;rt.anchoredPosition=position;rt.sizeDelta=size;}
        private static void Clear(Transform root){for(int i=root.childCount-1;i>=0;i--)Destroy(root.GetChild(i).gameObject);}
        private Sprite TextureSprite(Texture2D texture){if(texture==null)return null;return Sprite.Create(texture,new Rect(0,0,texture.width,texture.height),new Vector2(.5f,.5f),100);}
        private static Sprite CreateNineSlice(string name,Color center,Color edge){const int s=24,b=6;var texture=new Texture2D(s,s,TextureFormat.RGBA32,false){name=name,filterMode=FilterMode.Bilinear,wrapMode=TextureWrapMode.Clamp};var pixels=new Color[s*s];for(int y=0;y<s;y++)for(int x=0;x<s;x++){bool border=x<b||x>=s-b||y<b||y>=s-b;pixels[y*s+x]=border?edge:center;}texture.SetPixels(pixels);texture.Apply(false,true);return Sprite.Create(texture,new Rect(0,0,s,s),new Vector2(.5f,.5f),100,0,SpriteMeshType.FullRect,new Vector4(b,b,b,b));}
    }

    public sealed class SafeAreaLayout:MonoBehaviour
    {
        private Rect lastSafe;private Vector2Int lastScreen;
        private void Update(){if(lastSafe==Screen.safeArea&&lastScreen.x==Screen.width&&lastScreen.y==Screen.height)return;lastSafe=Screen.safeArea;lastScreen=new Vector2Int(Screen.width,Screen.height);var rt=(RectTransform)transform;rt.anchorMin=new Vector2(lastSafe.xMin/Screen.width,lastSafe.yMin/Screen.height);rt.anchorMax=new Vector2(lastSafe.xMax/Screen.width,lastSafe.yMax/Screen.height);rt.offsetMin=rt.offsetMax=Vector2.zero;}
    }
}
