using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace Nightfall.UnityMvp
{
    public sealed partial class NightfallGame
    {
        private enum TextSlotPreset { Title, Name, Button, Description, HudValue, Counter }
        private static class UiToken
        {
            public const float Title=44,Heading=28,Button=22,Body=18,Secondary=15,Counter=13;
            public static readonly Color Surface=new Color(.012f,.025f,.035f,.94f),SurfaceSoft=new Color(.018f,.045f,.058f,.88f),Cyan=new Color(.08f,.78f,.92f),Gold=new Color(1,.68f,.20f),Text=new Color(.94f,.97f,1),Muted=new Color(.68f,.76f,.80f);
        }

        private Canvas modernCanvas;private RectTransform safeAreaRoot;private TMP_FontAsset modernFont;private Sprite panelSprite,buttonSprite,barSprite,hpGradientSprite,panelArtSprite,cardArtSprite,buttonArtSprite;
        private GameObject menuScreen,heroScreen,hudScreen,upgradeScreen,petScreen,pauseScreen,endScreen;
        private TMP_Text timerText,killsText,heroNameText,hpText,xpText,levelText,petHudText,bossNameText,endTitleText,endStatsText,abilityNoticeText;
        private Image heroHudPortrait,hpFill,xpFill,petHudPortrait,bossFill,abilityNoticeIcon;private RectTransform bossRoot,loadoutRoot,upgradeCardsRoot,petModalContent,abilityNoticeRoot,joystickBase,joystickKnob;
        private Button pauseButton;private State uiRenderedState=(State)(-1);private int uiRenderedLevel=-1,uiRenderedPetCount=-1;private Enemy uiRenderedBoss;private bool showUiLayoutBounds,heroTransitionRunning;

        private void BuildModernUi()
        {
            Font selectedFont=GameLocalization.Current==GameLanguage.Chinese&&uiCjkFont!=null?uiCjkFont:uiFont;modernFont=TMP_FontAsset.CreateFontAsset(selectedFont);modernFont.atlasPopulationMode=AtlasPopulationMode.Dynamic;
            panelSprite=CreateNineSlice("UiPanel",new Color(.025f,.075f,.09f,1),new Color(.10f,.68f,.78f,1));buttonSprite=CreateNineSlice("UiButton",new Color(.04f,.12f,.15f,1),new Color(.18f,.82f,.92f,1));barSprite=CreateNineSlice("UiBar",new Color(.018f,.035f,.045f,1),new Color(.12f,.32f,.38f,1));hpGradientSprite=CreateHorizontalGradient("HpGradient",new Color(.32f,.008f,.018f,1),new Color(1f,.12f,.18f,1),new Color(1f,.48f,.34f,1));
            panelArtSprite=TextureSprite(uiPanelFrame);cardArtSprite=TextureSprite(uiCardFrame);buttonArtSprite=TextureSprite(uiButtonPlate);
            var canvasGo=new GameObject("NightfallCanvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));modernCanvas=canvasGo.GetComponent<Canvas>();modernCanvas.renderMode=RenderMode.ScreenSpaceOverlay;modernCanvas.sortingOrder=100;
            var scaler=canvasGo.GetComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1920,1080);scaler.screenMatchMode=CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;scaler.matchWidthOrHeight=.5f;
            if(FindAnyObjectByType<EventSystem>()==null)new GameObject("EventSystem",typeof(EventSystem),typeof(StandaloneInputModule));
            safeAreaRoot=Rect("SafeAreaRoot",canvasGo.transform);Stretch(safeAreaRoot,0,0,0,0);safeAreaRoot.gameObject.AddComponent<SafeAreaLayout>();
            menuScreen=BuildMenu();heroScreen=BuildHeroSelection();hudScreen=BuildHud();upgradeScreen=BuildUpgradeScreen();petScreen=BuildPetScreen();pauseScreen=BuildPauseScreen();endScreen=BuildEndScreen();
            SyncModernUi(true);
        }

        private GameObject BuildMenu()
        {
            var root=ScreenRoot("MenuScreen",true);AddBackground(root.transform);var panel=Panel("MenuPanel",root.transform,new Vector2(820,620));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);var menuTint=Rect("MenuInteriorTint",panel);Stretch(menuTint,42,42,42,42);var menuTintImage=menuTint.gameObject.AddComponent<Image>();menuTintImage.color=new Color(.18f,.20f,.22f,.54f);menuTintImage.raycastTarget=false;
            var logo=ImageNode("TitleWordmark",panel,uiTitleWordmark,true);SetAnchored(logo.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-70),new Vector2(590,154));logo.color=Color.white;
            var play=PrimaryButton(panel,"ИГРАТЬ",()=>SetUiState(State.HeroSelect),320,76);SetAnchored((RectTransform)play.transform,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,112),new Vector2(320,76));
            var language=PrimaryButton(panel,"LANGUAGE  "+GameLocalization.Code,CycleLanguage,220,54);SetAnchored((RectTransform)language.transform,new Vector2(1,0),new Vector2(1,0),new Vector2(-58,42),new Vector2(220,54));
            var volume=VolumeControl(panel,300,62);SetAnchored(volume,new Vector2(0,0),new Vector2(0,0),new Vector2(58,38),new Vector2(300,62));
            return root;
        }

        private GameObject BuildHeroSelection()
        {
            var root=ScreenRoot("HeroSelection",true);AddBackground(root.transform);var title=Text("Title",root.transform,"ВЫБЕРИТЕ ОПЕРАТИВНИКА",UiToken.Title,30,44,TextAlignmentOptions.Center);SetAnchored(title.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-48),new Vector2(1000,70));
            var subtitle=Text("Subtitle",root.transform,"Три боевых протокола. Один шанс пережить ночь.",UiToken.Secondary,12,15,TextAlignmentOptions.Center);SetAnchored(subtitle.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-112),new Vector2(900,38));
            var row=Horizontal("CharacterCards",root.transform,42,0,TextAnchor.MiddleCenter);SetAnchored(row,new Vector2(.5f,.5f),new Vector2(.5f,.5f),new Vector2(0,-24),new Vector2(1660,790));
            for(int i=0;i<3;i++){HeroKind kind=(HeroKind)i;BuildCharacterCard(row,kind);}return root;
        }

        private void BuildCharacterCard(RectTransform row,HeroKind kind)
        {
            var d=GameCatalog.Hero(kind);var card=Panel("Character_"+kind,row,new Vector2(500,760));var le=card.gameObject.AddComponent<LayoutElement>();le.preferredWidth=500;le.preferredHeight=760;
            var portraitBox=Rect("PortraitSlot",card);SetAnchored(portraitBox,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-44),new Vector2(390,270));var portrait=ImageNode("Portrait",portraitBox,heroPortraits[(int)kind],true);Stretch(portrait.rectTransform,18,18,8,8);
            var heroName=TextSlot("NameSlot",card,d.displayName,TextSlotPreset.Name,new Vector2(336,48),new Vector2(0,-340),FontStyles.Bold,new Color(.90f,.97f,1f),TextAlignmentOptions.Center);heroName.outlineColor=new Color(.05f,.72f,.92f,.72f);heroName.outlineWidth=.14f;
            TextSlot("StatsSlot",card,GameLocalization.Tr(d.subtitle)+"   •   "+d.hp.ToString("0")+" HP",TextSlotPreset.Counter,new Vector2(326,38),new Vector2(0,-390),FontStyles.Bold,UiToken.Muted,TextAlignmentOptions.Center);
            var description=TextSlot("DescriptionSlot",card,HeroAbilitiesCardSummary(kind),TextSlotPreset.Description,new Vector2(326,218),new Vector2(0,-518),FontStyles.Normal,UiToken.Text,TextAlignmentOptions.TopLeft);description.fontSizeMin=10;description.fontSizeMax=15;description.lineSpacing=-4;
            var button=PrimaryButton(card,"В БОЙ",()=>BeginHeroTransition(kind),310,66);SetAnchored((RectTransform)button.transform,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,42),new Vector2(310,66));
        }

        private void BeginHeroTransition(HeroKind kind){if(heroTransitionRunning)return;StartCoroutine(HeroTransitionRoutine(kind));}
        private IEnumerator HeroTransitionRoutine(HeroKind kind)
        {
            heroTransitionRunning=true;yield return new WaitForEndOfFrame();Texture2D capture=ScreenCapture.CaptureScreenshotAsTexture();if(capture==null){SetHero(kind);StartRun();heroTransitionRunning=false;yield break;}
            var overlay=Rect("HeroShatterTransition",modernCanvas.transform);Stretch(overlay,0,0,0,0);overlay.SetAsLastSibling();float width=overlay.rect.width,height=overlay.rect.height;Vector2 origin=new Vector2(((int)kind-1)*width*.285f,-height*.015f);var random=new System.Random(1709+(int)kind*811);Color crackColor=kind==HeroKind.Amelia?new Color(1f,.72f,.18f):kind==HeroKind.Sam?new Color(.92f,.08f,.18f):new Color(.10f,.80f,1f);
            const int edgeCount=24;var edge=new Vector2[edgeCount];int cursor=0;for(int i=0;i<=6;i++)edge[cursor++]=new Vector2(-width*.5f+width*i/6f,height*.5f);for(int i=1;i<=6;i++)edge[cursor++]=new Vector2(width*.5f,height*.5f-height*i/6f);for(int i=1;i<=6;i++)edge[cursor++]=new Vector2(width*.5f-width*i/6f,-height*.5f);for(int i=1;i<6;i++)edge[cursor++]=new Vector2(-width*.5f,-height*.5f+height*i/6f);
            var rings=new Vector2[3,edgeCount];for(int i=0;i<edgeCount;i++){Vector2 ray=edge[i]-origin;float near=.16f+(float)random.NextDouble()*.07f,middle=.43f+(float)random.NextDouble()*.12f;rings[0,i]=origin+ray*near;rings[1,i]=origin+ray*middle;rings[2,i]=edge[i];}
            var shards=new List<UiPolygonShard>(edgeCount*5);var velocities=new List<Vector2>(edgeCount*5);var spins=new List<Vector3>(edgeCount*5);var delays=new List<float>(edgeCount*5);
            Action<Vector2,Vector2,Vector2> addShard=(a,b,c)=>{Vector2 center=(a+b+c)/3f,min=Vector2.Min(a,Vector2.Min(b,c)),max=Vector2.Max(a,Vector2.Max(b,c));var rt=Rect("GlassShard",overlay);rt.anchorMin=rt.anchorMax=new Vector2(.5f,.5f);rt.pivot=Vector2.one*.5f;rt.anchoredPosition=center;rt.sizeDelta=max-min+Vector2.one*3;var shard=rt.gameObject.AddComponent<UiPolygonShard>();shard.source=capture;shard.points=new[]{a-center,b-center,c-center};shard.uvs=new[]{ScreenUv(a,width,height),ScreenUv(b,width,height),ScreenUv(c,width,height)};shard.color=Color.white;shards.Add(shard);Vector2 away=(center-origin).normalized;float distance=Vector2.Distance(center,origin)/Mathf.Max(width,height);velocities.Add(away*(250+(float)random.NextDouble()*430)+new Vector2(((float)random.NextDouble()-.5f)*90,40+(float)random.NextDouble()*130));spins.Add(new Vector3(((float)random.NextDouble()-.5f)*210,((float)random.NextDouble()-.5f)*210,((float)random.NextDouble()-.5f)*330));delays.Add(distance*.20f+(float)random.NextDouble()*.045f);};
            for(int i=0;i<edgeCount;i++){int next=(i+1)%edgeCount;addShard(origin,rings[0,i],rings[0,next]);for(int ring=0;ring<2;ring++){Vector2 a=rings[ring,i],b=rings[ring,next],c=rings[ring+1,next],d=rings[ring+1,i];if(random.NextDouble()>.5){addShard(a,b,c);addShard(a,c,d);}else{addShard(a,b,d);addShard(b,c,d);}}}
            var flash=Rect("CrackFlash",overlay);Stretch(flash,0,0,0,0);var flashImage=flash.gameObject.AddComponent<Image>();flashImage.raycastTarget=false;var cracks=new List<Image>(36);for(int i=0;i<9;i++){int ray=(i*edgeCount/9+(int)kind*2)%edgeCount;Vector2 a=origin,b=rings[0,ray],c=rings[1,ray];AddCrackSegment(overlay,a,b,crackColor,3.2f,cracks);AddCrackSegment(overlay,b,c,crackColor,2.1f,cracks);Vector2 branch=b+(rings[0,(ray+1)%edgeCount]-b)*(.28f+(float)random.NextDouble()*.22f);AddCrackSegment(overlay,b,branch,new Color(crackColor.r,crackColor.g,crackColor.b,.78f),1.35f,cracks);}
            float crackTime=0;while(crackTime<.30f){crackTime+=Time.unscaledDeltaTime;float t=Mathf.Clamp01(crackTime/.30f),pulse=Mathf.Sin(t*Mathf.PI);flashImage.color=new Color(crackColor.r,crackColor.g,crackColor.b,pulse*.13f);for(int i=0;i<cracks.Count;i++)cracks[i].color=new Color(cracks[i].color.r,cracks[i].color.g,cracks[i].color.b,Mathf.SmoothStep(0,1,t));yield return null;}
            SetHero(kind);StartRun();Destroy(flash.gameObject);for(int i=0;i<cracks.Count;i++)Destroy(cracks[i].gameObject);
            float elapsed=0,duration=1.12f;while(elapsed<duration){float dt=Time.unscaledDeltaTime;elapsed+=dt;for(int i=0;i<shards.Count;i++){float local=elapsed-delays[i];if(local<=0)continue;var rt=(RectTransform)shards[i].transform;Vector2 velocity=velocities[i];velocity.y-=760*dt;velocities[i]=velocity;rt.anchoredPosition+=velocity*dt;Vector3 spin=spins[i];rt.Rotate(spin.x*dt,spin.y*dt,spin.z*dt,Space.Self);float normalized=Mathf.Clamp01(local/(duration-delays[i])),alpha=1-Mathf.InverseLerp(.55f,1,normalized);rt.localScale=Vector3.one*Mathf.Lerp(1,.82f,normalized);shards[i].color=new Color(1,1,1,alpha);}yield return null;}
            Destroy(overlay.gameObject);Destroy(capture);heroTransitionRunning=false;
        }
        private static Vector2 ScreenUv(Vector2 point,float width,float height)=>new Vector2(point.x/width+.5f,point.y/height+.5f);
        private static void AddCrackSegment(Transform parent,Vector2 from,Vector2 to,Color color,float thickness,List<Image> result){Vector2 delta=to-from;var line=new GameObject("Fracture",typeof(RectTransform),typeof(Image));var rt=line.GetComponent<RectTransform>();rt.SetParent(parent,false);rt.anchorMin=rt.anchorMax=new Vector2(.5f,.5f);rt.pivot=new Vector2(0,.5f);rt.anchoredPosition=from;rt.sizeDelta=new Vector2(delta.magnitude,thickness);rt.localRotation=Quaternion.Euler(0,0,Mathf.Atan2(delta.y,delta.x)*Mathf.Rad2Deg);var image=line.GetComponent<Image>();image.color=new Color(color.r,color.g,color.b,0);image.raycastTarget=false;result.Add(image);}

        private GameObject BuildHud()
        {
            var root=ScreenRoot("GameplayHUD",false);
            var heroPanel=Panel("HeroHUD",root.transform,new Vector2(760,190));SetAnchored(heroPanel,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-22),heroPanel.sizeDelta);
            heroHudPortrait=ImageNode("HeroPortrait",heroPanel,null,true);SetAnchored(heroHudPortrait.rectTransform,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-22),new Vector2(132,132));
            heroNameText=Text("HeroName",heroPanel,"ГЕРОЙ",UiToken.Heading,18,27,TextAlignmentOptions.Left);SetAnchored(heroNameText.rectTransform,new Vector2(0,1),new Vector2(0,1),new Vector2(174,-18),new Vector2(360,38));heroNameText.fontStyle=FontStyles.Bold;
            levelText=Text("HeroLevel",heroPanel,"УРОВЕНЬ 1",UiToken.Secondary,12,16,TextAlignmentOptions.Left);SetAnchored(levelText.rectTransform,new Vector2(0,1),new Vector2(0,1),new Vector2(174,-54),new Vector2(240,26));levelText.fontStyle=FontStyles.Bold;
            hpFill=Bar(heroPanel,"HPBar",Color.white,360,32);hpFill.sprite=hpGradientSprite;SetAnchored((RectTransform)hpFill.transform.parent,new Vector2(0,1),new Vector2(0,1),new Vector2(174,-88),new Vector2(360,32));hpText=Text("HPValue",hpFill.transform.parent,"HP",UiToken.Secondary,12,16,TextAlignmentOptions.Center);Stretch(hpText.rectTransform,8,8,2,2);hpText.fontStyle=FontStyles.Bold;
            xpFill=Bar(heroPanel,"XPBar",new Color(.08f,.74f,.94f),360,28);SetAnchored((RectTransform)xpFill.transform.parent,new Vector2(0,1),new Vector2(0,1),new Vector2(174,-128),new Vector2(360,28));xpText=Text("XPValue",xpFill.transform.parent,"ОПЫТ",UiToken.Counter,11,14,TextAlignmentOptions.Center);Stretch(xpText.rectTransform,8,8,2,2);xpText.fontStyle=FontStyles.Bold;
            var petArea=Rect("PetArea",heroPanel);SetAnchored(petArea,new Vector2(1,1),new Vector2(1,1),new Vector2(-22,-20),new Vector2(164,146));petHudPortrait=ImageNode("PetPortrait",petArea,null,true);SetAnchored(petHudPortrait.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-4),new Vector2(82,82));petHudText=Text("PetStatus",petArea,"ВКУСНЯШКИ\n0 / 3",UiToken.Counter,10,13,TextAlignmentOptions.Center);SetAnchored(petHudText.rectTransform,new Vector2(0,0),new Vector2(1,0),new Vector2(0,22),new Vector2(0,54));petHudText.enableWordWrapping=true;petHudText.maxVisibleLines=2;petHudText.fontStyle=FontStyles.Bold;
            timerText=Text("Timer",root.transform,"00:00",UiToken.Heading,22,28,TextAlignmentOptions.Center);SetAnchored(timerText.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-30),new Vector2(240,54));killsText=Text("Kills",root.transform,"УНИЧТОЖЕНО: 0",UiToken.Body,14,18,TextAlignmentOptions.Right);SetAnchored(killsText.rectTransform,new Vector2(1,1),new Vector2(1,1),new Vector2(-210,-32),new Vector2(330,44));
            pauseButton=PrimaryButton(root.transform,"ПАУЗА",()=>SetUiState(State.Paused),180,58);SetAnchored((RectTransform)pauseButton.transform,new Vector2(1,1),new Vector2(1,1),new Vector2(-24,-24),new Vector2(180,58));
            var qa=Horizontal("QaTools",root.transform,10,0,TextAnchor.MiddleLeft);SetAnchored(qa,new Vector2(0,1),new Vector2(0,1),new Vector2(24,-214),new Vector2(850,56));PrimaryButton(qa,"QA GOD",()=>qaInvulnerable=!qaInvulnerable,170,52);PrimaryButton(qa,"QA +1 LEVEL",QaLevelUp,195,52);PrimaryButton(qa,"QA PET",QaUnlockPet,165,52);PrimaryButton(qa,"QA VFX",QaPreviewNextAbility,165,52);
            bossRoot=Panel("BossHUD",root.transform,new Vector2(760,92));SetAnchored(bossRoot,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-102),bossRoot.sizeDelta);bossNameText=Text("BossName",bossRoot,"БОСС",UiToken.Body,14,18,TextAlignmentOptions.Center);SetAnchored(bossNameText.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-16),new Vector2(660,28));bossFill=Bar(bossRoot,"BossBar",new Color(.85f,.08f,.12f),660,20);SetAnchored(bossFill.transform.parent as RectTransform,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,18),new Vector2(660,20));
            loadoutRoot=Vertical("Loadout",root.transform,8,8,TextAnchor.LowerRight);SetAnchored(loadoutRoot,new Vector2(1,0),new Vector2(1,0),new Vector2(-24,24),new Vector2(460,320));
            abilityNoticeText=Text("AbilityNotice",root.transform,"",UiToken.Secondary,12,15,TextAlignmentOptions.Left);abilityNoticeRoot=Panel("AbilityNoticePanel",root.transform,new Vector2(430,72));SetAnchored(abilityNoticeRoot,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-205),abilityNoticeRoot.sizeDelta);abilityNoticeIcon=ImageNode("Icon",abilityNoticeRoot,null,true);SetAnchored(abilityNoticeIcon.rectTransform,new Vector2(0,.5f),new Vector2(0,.5f),new Vector2(16,0),new Vector2(48,48));abilityNoticeText.transform.SetParent(abilityNoticeRoot,false);SetAnchored(abilityNoticeText.rectTransform,new Vector2(0,0),new Vector2(1,1),Vector2.zero,Vector2.zero);abilityNoticeText.rectTransform.offsetMin=new Vector2(78,10);abilityNoticeText.rectTransform.offsetMax=new Vector2(-14,-10);abilityNoticeRoot.gameObject.SetActive(false);
            joystickBase=Panel("TouchJoystick",root.transform,new Vector2(150,150),new Color(.02f,.08f,.10f,.55f));joystickBase.pivot=Vector2.one*.5f;joystickBase.gameObject.SetActive(false);joystickKnob=Panel("Knob",joystickBase,new Vector2(64,64),new Color(.10f,.75f,.88f,.75f));Anchor(joystickKnob,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);
            return root;
        }

        private GameObject BuildUpgradeScreen(){var root=ScreenRoot("UpgradeScreen",false,true);var panel=Panel("UpgradePanel",root.transform,new Vector2(1500,760));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);LayoutText(Vertical("Header",panel,0,0,TextAnchor.UpperCenter),"НОВЫЙ УРОВЕНЬ",UiToken.Title,30,44,68,FontStyles.Bold);upgradeCardsRoot=Horizontal("Cards",panel,34,0,TextAnchor.MiddleCenter);SetAnchored(upgradeCardsRoot,new Vector2(.5f,.5f),new Vector2(.5f,.5f),new Vector2(0,-35),new Vector2(1330,560));return root;}
        private GameObject BuildPetScreen(){var root=ScreenRoot("PetScreen",false,true);petModalContent=Panel("PetModal",root.transform,new Vector2(1050,680));Anchor(petModalContent,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);return root;}
        private GameObject BuildPauseScreen(){var root=ScreenRoot("PauseScreen",false,true);var panel=Panel("PausePanel",root.transform,new Vector2(650,650));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);var stack=Vertical("Content",panel,22,12,TextAnchor.MiddleCenter);Stretch(stack,75,75,42,42);LayoutText(stack,"ПАУЗА",UiToken.Title,30,44,72,FontStyles.Bold);PrimaryButton(stack,"ПРОДОЛЖИТЬ",()=>SetUiState(State.Playing),360,64);VolumeControl(stack,360,68,true);PrimaryButton(stack,"LANGUAGE  "+GameLocalization.Code,CycleLanguage,360,58);PrimaryButton(stack,"НАЧАТЬ ЗАНОВО",StartRun,360,64);PrimaryButton(stack,"ВЫБОР ГЕРОЯ",()=>{player.SetActive(false);SetUiState(State.HeroSelect);},360,64);return root;}
        private GameObject BuildEndScreen(){var root=ScreenRoot("EndScreen",false,true);var panel=Panel("EndPanel",root.transform,new Vector2(820,610));Anchor(panel,Vector2.one*.5f,Vector2.one*.5f,Vector2.zero);var stack=Vertical("Content",panel,24,16,TextAnchor.MiddleCenter);Stretch(stack,70,70,54,54);endTitleText=LayoutText(stack,"ПОБЕДА",UiToken.Title,30,48,90,FontStyles.Bold);endStatsText=LayoutText(stack,"Уничтожено: 0",UiToken.Heading,18,28,60);PrimaryButton(stack,"ЕЩЁ РАЗ",()=>SetUiState(State.HeroSelect),340,68);PrimaryButton(stack,"ГЛАВНОЕ МЕНЮ",ReturnToMainMenu,340,68);return root;}

        private void SyncModernUi(bool force=false)
        {
            if(modernCanvas==null||safeAreaRoot==null||menuScreen==null||heroScreen==null||hudScreen==null||heroNameText==null){if(!Application.isPlaying)return;var stale=GameObject.Find("NightfallCanvas");if(stale!=null)Destroy(stale);BuildModernUi();return;}if(hero==null){if(player==null||spriteFactory==null||characterVisual==null)return;SetHero(HeroKind.Amelia);}Rect safe=Screen.safeArea;safeAreaRoot.anchorMin=new Vector2(safe.xMin/Screen.width,safe.yMin/Screen.height);safeAreaRoot.anchorMax=new Vector2(safe.xMax/Screen.width,safe.yMax/Screen.height);
            if(force||uiRenderedState!=state){uiRenderedState=state;menuScreen.SetActive(state==State.Menu);heroScreen.SetActive(state==State.HeroSelect);hudScreen.SetActive(state==State.Playing);upgradeScreen.SetActive(state==State.Upgrade);petScreen.SetActive(state==State.PetUnlock);pauseScreen.SetActive(state==State.Paused);endScreen.SetActive(state==State.Dead||state==State.Victory);if(state==State.Upgrade)RenderUpgradeCards();if(state==State.PetUnlock)RenderPetModal();if(state==State.Dead||state==State.Victory){endTitleText.text=GameLocalization.Tr(state==State.Victory?"ПОБЕДА":"ОПЕРАТИВНИК ПОГИБ");endStatsText.text=LocalizedCount("Уничтожено целей: ","Targets eliminated: ","消灭目标：",kills);}}
            if(state!=State.Playing)return;heroNameText.text=GameLocalization.Tr(hero.displayName);levelText.text=LocalizedCount("УРОВЕНЬ ","LEVEL ","等级 ",level);hpText.text="HP  "+Mathf.CeilToInt(hp)+" / "+Mathf.CeilToInt(maxHp);hpFill.fillAmount=maxHp>0?hp/maxHp:0;xpText.text=(GameLocalization.Current==GameLanguage.Russian?"ОПЫТ":GameLocalization.Current==GameLanguage.English?"XP":"经验")+"  "+xp+" / "+xpNeed;xpFill.fillAmount=xpNeed>0?(float)xp/xpNeed:0;timerText.text=$"{(int)(runTime/60):00}:{(int)(runTime%60):00}";killsText.text=LocalizedCount("УНИЧТОЖЕНО: ","ELIMINATED: ","消灭：",kills);
            if(heroHudPortrait!=null)heroHudPortrait.sprite=TextureSprite(heroPortraits[(int)hero.kind]);petHudPortrait.gameObject.SetActive(petUnlocked);petHudPortrait.sprite=petUnlocked?TextureSprite(petPortrait):null;petHudText.text=petUnlocked?GameLocalization.Tr(petDefinition.displayName)+"\n"+(GameLocalization.Current==GameLanguage.Russian?"УР. ":GameLocalization.Current==GameLanguage.English?"LV. ":"等级 ")+petLevel+"  •  "+(petLevel>=PetCatalog.MaxLevel?"MAX":treatsCollected+" / 3"):(GameLocalization.Current==GameLanguage.Russian?"ВКУСНЯШКИ":GameLocalization.Current==GameLanguage.English?"TREATS":"零食")+"\n"+treatsCollected+" / 3";
            bossRoot.gameObject.SetActive(currentBoss!=null);if(currentBoss!=null){bossNameText.text=GameLocalization.Tr(currentBoss.boss.name);bossFill.fillAmount=currentBoss.maxHp>0?currentBoss.hp/currentBoss.maxHp:0;}
            bool showAbility=abilityFlashTimer>0;abilityNoticeRoot.gameObject.SetActive(showAbility);if(showAbility){abilityNoticeText.text=abilityFlash;abilityNoticeIcon.sprite=abilityFlashSlot>=0?TextureSprite(UiIcon(AbilityIconId(hero.kind,abilityFlashSlot))):abilityFlashSlot==-2?petNotificationSprite:null;abilityNoticeIcon.gameObject.SetActive(abilityNoticeIcon.sprite!=null);}
            bool showJoystick=joystickFinger>=0;joystickBase.gameObject.SetActive(showJoystick);if(showJoystick){Vector2 screenPos=joystickOrigin;RectTransformUtility.ScreenPointToLocalPointInRectangle(safeAreaRoot,screenPos,modernCanvas.worldCamera,out Vector2 local);joystickBase.anchoredPosition=local;joystickKnob.anchoredPosition=Vector2.ClampMagnitude(moveInput,1)*42f;}
            if(force||uiRenderedLevel!=level||uiRenderedPetCount!=treatsCollected||uiRenderedBoss!=currentBoss){uiRenderedLevel=level;uiRenderedPetCount=treatsCollected;uiRenderedBoss=currentBoss;RenderLoadout();}
        }

        private void RenderUpgradeCards(){Clear(upgradeCardsRoot);for(int i=0;i<3;i++){int index=i;var u=offered[i];if(u==null)continue;var card=Panel("UpgradeCard_"+i,upgradeCardsRoot,new Vector2(410,520));var le=card.gameObject.AddComponent<LayoutElement>();le.preferredWidth=410;le.preferredHeight=520;var icon=ImageNode("IconSlot",card,UiIcon(u.icon),true);SetAnchored(icon.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(0,-66),new Vector2(92,92));var title=TextSlot("NameSlot",card,u.name,TextSlotPreset.Name,new Vector2(270,62),new Vector2(0,-148),FontStyles.Bold,UiToken.Text,TextAlignmentOptions.Center);title.fontSizeMin=10;title.fontSizeMax=22;int next=u.ability>=0?abilityRanks[u.ability]+1:0;if(u.ability>=0)TextSlot("RankSlot",card,RankLabel(next),TextSlotPreset.Counter,new Vector2(250,28),new Vector2(0,-198),FontStyles.Bold,UiToken.Gold,TextAlignmentOptions.Center);var description=TextSlot("DescriptionSlot",card,u.description,TextSlotPreset.Description,new Vector2(250,156),new Vector2(0,-300),FontStyles.Normal,UiToken.Text,TextAlignmentOptions.TopLeft);description.margin=new Vector4(10,4,10,4);description.fontSizeMin=10;description.fontSizeMax=14;description.lineSpacing=-3;var select=PrimaryButton(card,"ВЫБРАТЬ",()=>SelectUpgrade(index),250,58);SetAnchored((RectTransform)select.transform,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,34),new Vector2(250,58));}}
        private void RenderPetModal(){Clear(petModalContent);TextSlot("TitleSlot",petModalContent,"ФАМИЛЬЯР ОТКЛИКНУЛСЯ",TextSlotPreset.Title,new Vector2(820,64),new Vector2(0,-48),FontStyles.Bold,UiToken.Text,TextAlignmentOptions.Center);var portrait=ImageNode("PetPortrait",petModalContent,petPortrait,true);SetAnchored(portrait.rectTransform,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(-270,-150),new Vector2(280,280));TextSlot("NameSlot",petModalContent,petDefinition.displayName,TextSlotPreset.Name,new Vector2(320,52),new Vector2(-270,-438),FontStyles.Bold,UiToken.Gold,TextAlignmentOptions.Center);var divider=Rect("PetDivider",petModalContent);SetAnchored(divider,new Vector2(.5f,1),new Vector2(.5f,1),new Vector2(-35,-175),new Vector2(2,300));var dividerImage=divider.gameObject.AddComponent<Image>();dividerImage.color=new Color(.08f,.78f,.92f,.48f);dividerImage.raycastTarget=false;var description=TextSlot("DescriptionSlot",petModalContent,petDefinition.description,TextSlotPreset.Description,new Vector2(420,150),new Vector2(230,-190),FontStyles.Normal,UiToken.Text,TextAlignmentOptions.TopLeft);description.fontSizeMin=13;description.fontSizeMax=18;description.maxVisibleLines=6;var stats=TextSlot("StatsSlot",petModalContent,"АВТОАТАКА   20% урона героя\nЭХО НАВЫКА   12%\nРОЛЬ   наземный спутник",TextSlotPreset.Description,new Vector2(420,130),new Vector2(230,-370),FontStyles.Bold,UiToken.Muted,TextAlignmentOptions.TopLeft);stats.fontSizeMin=12;stats.fontSizeMax=16;stats.maxVisibleLines=4;var accept=PrimaryButton(petModalContent,"ПРИНЯТЬ ФАМИЛЬЯРА",UnlockPet,390,68);SetAnchored((RectTransform)accept.transform,new Vector2(.5f,0),new Vector2(.5f,0),new Vector2(0,46),new Vector2(390,68));}
        private void RenderLoadout(){Clear(loadoutRoot);int learned=0;for(int i=0;i<5;i++)if(abilityRanks[i]>0)learned++;if(learned==0)return;for(int i=0;i<5;i++){if(abilityRanks[i]<=0)continue;var row=Panel("Ability_"+i,loadoutRoot,new Vector2(430,48),UiToken.SurfaceSoft);row.gameObject.AddComponent<LayoutElement>().preferredHeight=48;var icon=ImageNode("Icon",row,UiIcon(AbilityIconId(hero.kind,i)),true);SetAnchored(icon.rectTransform,new Vector2(0,.5f),new Vector2(0,.5f),new Vector2(8,0),new Vector2(36,36));var label=Text("Label",row,AbilityName(hero.kind,i)+"   "+RankLabel(abilityRanks[i]),UiToken.Counter,11,13,TextAlignmentOptions.Left);Stretch(label.rectTransform,54,10,7,7);}}
        private void SetUiState(State value){state=value;SyncModernUi(true);}
        private void ReturnToMainMenu(){foreach(var enemy in enemies){enemy.active=false;if(enemy.go!=null)enemy.go.SetActive(false);}foreach(var projectile in projectiles){projectile.active=false;if(projectile.go!=null)projectile.go.SetActive(false);}currentBoss=null;if(player!=null)player.SetActive(false);state=State.Menu;SyncModernUi(true);}
        public void DebugPreviewUi(string screen)
        {
            if(hero==null)SetHero(HeroKind.Amelia);
            if(screen=="Menu")state=State.Menu;else if(screen=="HeroSelect")state=State.HeroSelect;else if(screen=="HUD"){if(!player.activeSelf)StartRun();state=State.Playing;}else if(screen=="Upgrade"){RollUpgrades();state=State.Upgrade;}else if(screen=="Pet"){petDefinition=PetCatalog.ForOwner(hero.id);petPortrait=Resources.Load<Texture2D>(petDefinition.portraitResource);state=State.PetUnlock;}else if(screen=="Pause")state=State.Paused;else if(screen=="Boss"){if(!player.activeSelf)StartRun();if(currentBoss==null)SpawnBoss(BossKind.EarthDragon);state=State.Playing;}else if(screen=="End")state=State.Victory;SyncModernUi(true);
        }
        public string RunUiLayoutAudit()
        {
            if(modernCanvas==null)return "Canvas is not initialized";Canvas.ForceUpdateCanvases();int issues=0,labels=0,buttons=0;var safe=safeAreaRoot.rect;
            foreach(var label in modernCanvas.GetComponentsInChildren<TMP_Text>(true)){labels++;if(!label.gameObject.activeInHierarchy)continue;label.ForceMeshUpdate();var rt=label.rectTransform;var bounds=label.textBounds.size;if(bounds.x>rt.rect.width+1||bounds.y>rt.rect.height+1){Debug.LogWarning("UI_AUDIT text outside slot: "+HierarchyPath(rt)+$" text={bounds.x:0}x{bounds.y:0} slot={rt.rect.width:0}x{rt.rect.height:0}");issues++;}if(!label.enableWordWrapping&&label.textInfo.lineCount>1){Debug.LogWarning("UI_AUDIT unexpected wrap: "+HierarchyPath(rt));issues++;}}
            foreach(var button in modernCanvas.GetComponentsInChildren<Button>(true)){buttons++;if(button.targetGraphic==null){Debug.LogWarning("UI_AUDIT button has no visual: "+HierarchyPath(button.transform));issues++;}}
            string result=$"UI AUDIT: {issues} issue(s), {labels} TMP labels, {buttons} buttons, SafeArea {safe.width:0}x{safe.height:0}";Debug.Log(result);return result;
        }
        public string RunUiLongStringAudit(){if(modernCanvas==null)return "Canvas is not initialized";var labels=modernCanvas.GetComponentsInChildren<TMP_Text>(true);var original=new string[labels.Length];for(int i=0;i<labels.Length;i++){original[i]=labels[i].text;if(labels[i].transform.parent!=null&&labels[i].transform.parent.name.Contains("NameSlot"))labels[i].text="ОЧЕНЬ ДЛИННОЕ ИМЯ ОПЕРАТИВНИКА БЮРО";else if(labels[i].transform.parent!=null&&labels[i].transform.parent.name.Contains("DescriptionSlot"))labels[i].text="Длинное тестовое описание способности проверяет перенос строк, границы фиксированного контейнера и то, что соседние элементы интерфейса никогда не сдвигаются из-за объёма текста.";}string result=RunUiLayoutAudit();for(int i=0;i<labels.Length;i++)labels[i].text=original[i];Canvas.ForceUpdateCanvases();Debug.Log("UI LONG STRING "+result);return result;}
        public void SetUiLayoutBounds(bool visible){showUiLayoutBounds=visible;if(modernCanvas==null)return;foreach(var marker in modernCanvas.GetComponentsInChildren<UiLayoutBounds>(true))marker.visible=visible;}
        private static string HierarchyPath(Transform value){string path=value.name;while(value.parent!=null){value=value.parent;path=value.name+"/"+path;}return path;}

        private GameObject ScreenRoot(string name,bool active,bool dim=false){var go=new GameObject(name,typeof(RectTransform));go.transform.SetParent(safeAreaRoot,false);Stretch((RectTransform)go.transform,0,0,0,0);if(dim){var image=go.AddComponent<Image>();image.color=new Color(0,0,0,.72f);}go.SetActive(active);return go;}
        private void AddBackground(Transform parent){var raw=new GameObject("Background",typeof(RectTransform),typeof(RawImage)).GetComponent<RawImage>();raw.transform.SetParent(parent,false);Stretch(raw.rectTransform,0,0,0,0);raw.texture=uiMenuBackground;raw.uvRect=new Rect(0,0,1,1);raw.color=new Color(.78f,.82f,.86f,1);raw.raycastTarget=false;}
        private RectTransform Panel(string name,Transform parent,Vector2 size,Color? color=null){var rt=Rect(name,parent);rt.sizeDelta=size;var image=rt.gameObject.AddComponent<Image>();bool card=name.StartsWith("Character_")||name.StartsWith("UpgradeCard_");bool large=size.x>=600&&size.y>=400;image.sprite=card&&cardArtSprite!=null?cardArtSprite:large&&panelArtSprite!=null?panelArtSprite:panelSprite;image.type=(card&&cardArtSprite!=null)||(large&&panelArtSprite!=null)?Image.Type.Simple:Image.Type.Sliced;image.color=color??Color.white;return rt;}
        private void CycleLanguage(){GameLocalization.Cycle();var oldCanvas=modernCanvas;modernCanvas=null;if(oldCanvas!=null)Destroy(oldCanvas.gameObject);uiRenderedState=(State)(-1);BuildModernUi();}
        private RectTransform VolumeControl(Transform parent,float width,float height,bool layout=false)
        {
            var root=Rect("MasterVolume",parent);root.sizeDelta=new Vector2(width,height);if(layout){var le=root.gameObject.AddComponent<LayoutElement>();le.preferredWidth=width;le.preferredHeight=height;le.minHeight=height;}
            var frame=Rect("OrnateFrame",root);Stretch(frame,0,0,0,0);var frameImage=frame.gameObject.AddComponent<Image>();frameImage.sprite=buttonArtSprite!=null?buttonArtSprite:buttonSprite;frameImage.type=buttonArtSprite!=null?Image.Type.Simple:Image.Type.Sliced;frameImage.color=new Color(.88f,.91f,.92f,.96f);frameImage.raycastTarget=false;
            var label=Text("VolumeLabel",root,"",UiToken.Counter,10,14,TextAlignmentOptions.Center);SetAnchored(label.rectTransform,new Vector2(.06f,.16f),new Vector2(.40f,.84f),Vector2.zero,Vector2.zero);label.fontStyle=FontStyles.Bold;label.color=new Color(.94f,.91f,.78f);
            var track=Rect("Track",root);SetAnchored(track,new Vector2(.43f,.5f),new Vector2(.91f,.5f),Vector2.zero,new Vector2(0,16));var trackImage=track.gameObject.AddComponent<Image>();trackImage.sprite=buttonSprite;trackImage.type=Image.Type.Sliced;trackImage.color=new Color(.045f,.075f,.082f,.98f);
            for(int i=0;i<5;i++){var tick=Rect("Tick_"+i,track);SetAnchored(tick,new Vector2(i*.25f,.5f),new Vector2(i*.25f,.5f),Vector2.zero,new Vector2(2,10));var tickImage=tick.gameObject.AddComponent<Image>();tickImage.color=new Color(1f,.68f,.20f,.50f);tickImage.raycastTarget=false;}
            var fillArea=Rect("FillArea",track);Stretch(fillArea,4,4,4,4);var fill=Rect("Fill",fillArea);Stretch(fill,0,0,0,0);var fillImage=fill.gameObject.AddComponent<Image>();fillImage.sprite=barSprite;fillImage.type=Image.Type.Sliced;fillImage.color=new Color(.08f,.80f,.92f,1);
            var handleArea=Rect("HandleArea",track);Stretch(handleArea,8,8,0,0);var handle=Rect("Handle",handleArea);handle.sizeDelta=new Vector2(22,22);handle.localRotation=Quaternion.Euler(0,0,45);var handleImage=handle.gameObject.AddComponent<Image>();handleImage.sprite=buttonSprite;handleImage.type=Image.Type.Sliced;handleImage.color=UiToken.Gold;var gem=Rect("Gem",handle);Stretch(gem,5,5,5,5);var gemImage=gem.gameObject.AddComponent<Image>();gemImage.color=new Color(.10f,.88f,1f,1);gemImage.raycastTarget=false;
            var slider=root.gameObject.AddComponent<Slider>();slider.fillRect=fill;slider.handleRect=handle;slider.targetGraphic=handleImage;slider.direction=Slider.Direction.LeftToRight;slider.minValue=0;slider.maxValue=1;slider.wholeNumbers=false;slider.value=masterVolume;
            Action<float> refresh=value=>{masterVolume=Mathf.Clamp01(value);AudioListener.volume=masterVolume;label.text=GameLocalization.Tr("ЗВУК")+"   "+Mathf.RoundToInt(masterVolume*100)+"%";PlayerPrefs.SetFloat("BureauBreakers.MasterVolume",masterVolume);PlayerPrefs.Save();};slider.onValueChanged.AddListener(value=>refresh(value));refresh(masterVolume);return root;
        }
        private static string LocalizedCount(string ru,string en,string zh,int value)=>GameLocalization.Current==GameLanguage.Russian?ru+value:GameLocalization.Current==GameLanguage.English?en+value:zh+value;
        private static string RankLabel(int rank)=>rank>=6?GameLocalization.Tr("ЭВОЛЮЦИЯ"):(GameLocalization.Current==GameLanguage.Russian?"РАНГ ":GameLocalization.Current==GameLanguage.English?"RANK ":"等级 ")+rank+" / 6";
        private Button PrimaryButton(Transform parent,string label,Action action,float width,float height){var rt=Rect("Button_"+label,parent);rt.sizeDelta=new Vector2(width,height);var background=Rect("Background",rt);Stretch(background,0,0,0,0);var image=background.gameObject.AddComponent<Image>();image.sprite=buttonArtSprite!=null?buttonArtSprite:buttonSprite;image.type=buttonArtSprite!=null?Image.Type.Simple:Image.Type.Sliced;var button=rt.gameObject.AddComponent<Button>();button.targetGraphic=image;var colors=button.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1.12f,1.12f,1.12f);colors.pressedColor=new Color(.62f,.78f,.82f);colors.disabledColor=new Color(.25f,.3f,.32f,.7f);colors.fadeDuration=.08f;button.colors=colors;button.onClick.AddListener(()=>action());var content=Rect("Content",rt);Stretch(content,18,18,8,8);var text=TextSlot("LabelSlot",content,label,TextSlotPreset.Button,Vector2.zero,Vector2.zero,FontStyles.Bold,UiToken.Text,TextAlignmentOptions.Center,true);var le=rt.gameObject.AddComponent<LayoutElement>();le.preferredWidth=width;le.preferredHeight=height;le.minHeight=height;le.flexibleHeight=0;return button;}
        private RectTransform Vertical(string name,Transform parent,float padding,float spacing,TextAnchor align){var rt=Rect(name,parent);var layout=rt.gameObject.AddComponent<VerticalLayoutGroup>();layout.padding=new RectOffset((int)padding,(int)padding,(int)padding,(int)padding);layout.spacing=spacing;layout.childAlignment=align;layout.childControlWidth=true;layout.childControlHeight=false;layout.childForceExpandWidth=true;layout.childForceExpandHeight=false;return rt;}
        private RectTransform Horizontal(string name,Transform parent,float spacing,float padding,TextAnchor align){var rt=Rect(name,parent);var layout=rt.gameObject.AddComponent<HorizontalLayoutGroup>();layout.padding=new RectOffset((int)padding,(int)padding,(int)padding,(int)padding);layout.spacing=spacing;layout.childAlignment=align;layout.childControlWidth=false;layout.childControlHeight=false;layout.childForceExpandWidth=false;layout.childForceExpandHeight=false;return rt;}
        private TMP_Text LayoutText(Transform parent,string value,float size,float min,float max,float height,FontStyles style=FontStyles.Normal,Color? color=null,TextAlignmentOptions alignment=TextAlignmentOptions.Center){var slot=Rect("TextSlot",parent);var le=slot.gameObject.AddComponent<LayoutElement>();le.preferredHeight=height;le.minHeight=height;le.flexibleHeight=0;var marker=slot.gameObject.AddComponent<UiLayoutBounds>();marker.kind=alignment==TextAlignmentOptions.TopLeft?UiLayoutBounds.Kind.Description:UiLayoutBounds.Kind.Text;marker.visible=showUiLayoutBounds;var text=Text("Text",slot,value,size,min,max,alignment);Stretch(text.rectTransform,8,8,3,3);text.fontStyle=style;text.color=color??UiToken.Text;text.enableWordWrapping=alignment==TextAlignmentOptions.TopLeft||alignment==TextAlignmentOptions.Left;text.maxVisibleLines=text.enableWordWrapping?8:1;return text;}
        private TMP_Text TextSlot(string name,Transform parent,string value,TextSlotPreset preset,Vector2 size,Vector2 position,FontStyles style,Color color,TextAlignmentOptions alignment,bool stretch=false){var slot=Rect(name,parent);if(stretch)Stretch(slot,0,0,0,0);else SetAnchored(slot,new Vector2(.5f,1),new Vector2(.5f,1),position,size);var marker=slot.gameObject.AddComponent<UiLayoutBounds>();marker.kind=preset==TextSlotPreset.Button?UiLayoutBounds.Kind.Button:preset==TextSlotPreset.Description?UiLayoutBounds.Kind.Description:UiLayoutBounds.Kind.Text;marker.visible=showUiLayoutBounds;var text=Text("TMP_Label",slot,value,preset==TextSlotPreset.Title?UiToken.Title:preset==TextSlotPreset.Name?UiToken.Heading:preset==TextSlotPreset.Button?UiToken.Button:preset==TextSlotPreset.Description?UiToken.Body:preset==TextSlotPreset.HudValue?UiToken.Secondary:UiToken.Counter,preset==TextSlotPreset.Title?28:preset==TextSlotPreset.Name?17:preset==TextSlotPreset.Button?15:preset==TextSlotPreset.Description?12:10,preset==TextSlotPreset.Title?44:preset==TextSlotPreset.Name?28:preset==TextSlotPreset.Button?22:preset==TextSlotPreset.Description?18:preset==TextSlotPreset.HudValue?16:13,alignment);Stretch(text.rectTransform,8,8,4,4);text.fontStyle=style;text.color=color;text.enableWordWrapping=preset==TextSlotPreset.Description;text.overflowMode=TextOverflowModes.Ellipsis;text.maxVisibleLines=preset==TextSlotPreset.Description?8:1;return text;}
        private TMP_Text Text(string name,Transform parent,string value,float size,float min,float max,TextAlignmentOptions alignment){var rt=Rect(name,parent);var text=rt.gameObject.AddComponent<TextMeshProUGUI>();text.font=modernFont;text.text=GameLocalization.Tr(value);text.fontSize=size;text.enableAutoSizing=true;text.fontSizeMin=min;text.fontSizeMax=max;text.color=UiToken.Text;text.alignment=alignment;text.enableWordWrapping=false;text.maxVisibleLines=1;text.overflowMode=TextOverflowModes.Ellipsis;text.raycastTarget=false;text.margin=new Vector4(2,2,2,2);return text;}
        private Image ImageNode(string name,Transform parent,Texture2D texture,bool preserve){var rt=Rect(name,parent);var image=rt.gameObject.AddComponent<Image>();image.sprite=TextureSprite(texture);image.preserveAspect=preserve;image.raycastTarget=false;return image;}
        private Image Bar(Transform parent,string name,Color fillColor,float width,float height){var bg=Rect(name,parent);bg.sizeDelta=new Vector2(width,height);bg.gameObject.AddComponent<LayoutElement>().preferredHeight=height;var image=bg.gameObject.AddComponent<Image>();image.sprite=barSprite;image.type=Image.Type.Sliced;image.color=Color.white;var fillRt=Rect("Fill",bg);Stretch(fillRt,3,3,3,3);var fill=fillRt.gameObject.AddComponent<Image>();fill.sprite=barSprite;fill.type=Image.Type.Filled;fill.fillMethod=Image.FillMethod.Horizontal;fill.color=fillColor;return fill;}
        private void Spacer(Transform parent,float height){var rt=Rect("Spacer",parent);rt.gameObject.AddComponent<LayoutElement>().preferredHeight=height;}
        private static RectTransform Rect(string name,Transform parent){var go=new GameObject(name,typeof(RectTransform));go.transform.SetParent(parent,false);return (RectTransform)go.transform;}
        private static void Stretch(RectTransform rt,float left,float right,float top,float bottom){rt.anchorMin=Vector2.zero;rt.anchorMax=Vector2.one;rt.offsetMin=new Vector2(left,bottom);rt.offsetMax=new Vector2(-right,-top);}
        private static void Anchor(RectTransform rt,Vector2 min,Vector2 max,Vector2 position){rt.anchorMin=min;rt.anchorMax=max;rt.pivot=(min+max)*.5f;rt.anchoredPosition=position;}
        private static void SetAnchored(RectTransform rt,Vector2 min,Vector2 max,Vector2 position,Vector2 size){rt.anchorMin=min;rt.anchorMax=max;rt.pivot=(min+max)*.5f;rt.anchoredPosition=position;rt.sizeDelta=size;}
        private static void Clear(Transform root){for(int i=root.childCount-1;i>=0;i--)Destroy(root.GetChild(i).gameObject);}
        private Sprite TextureSprite(Texture2D texture){if(texture==null)return null;return Sprite.Create(texture,new Rect(0,0,texture.width,texture.height),new Vector2(.5f,.5f),100);}
        private static Sprite CreateNineSlice(string name,Color center,Color edge){const int s=24,b=6;var texture=new Texture2D(s,s,TextureFormat.RGBA32,false){name=name,filterMode=FilterMode.Bilinear,wrapMode=TextureWrapMode.Clamp};var pixels=new Color[s*s];for(int y=0;y<s;y++)for(int x=0;x<s;x++){bool border=x<b||x>=s-b||y<b||y>=s-b;pixels[y*s+x]=border?edge:center;}texture.SetPixels(pixels);texture.Apply(false,true);return Sprite.Create(texture,new Rect(0,0,s,s),new Vector2(.5f,.5f),100,0,SpriteMeshType.FullRect,new Vector4(b,b,b,b));}
        private static Sprite CreateHorizontalGradient(string name,Color left,Color middle,Color right){const int width=128,height=8;var texture=new Texture2D(width,height,TextureFormat.RGBA32,false){name=name,filterMode=FilterMode.Bilinear,wrapMode=TextureWrapMode.Clamp};var pixels=new Color[width*height];for(int y=0;y<height;y++)for(int x=0;x<width;x++){float t=x/(float)(width-1);Color baseColor=t<.72f?Color.Lerp(left,middle,t/.72f):Color.Lerp(middle,right,(t-.72f)/.28f);float highlight=1f+Mathf.Sin(y/(float)(height-1)*Mathf.PI)*.14f;pixels[y*width+x]=new Color(Mathf.Clamp01(baseColor.r*highlight),Mathf.Clamp01(baseColor.g*highlight),Mathf.Clamp01(baseColor.b*highlight),1);}texture.SetPixels(pixels);texture.Apply(false,true);return Sprite.Create(texture,new Rect(0,0,width,height),new Vector2(.5f,.5f),100);}
    }

    public sealed class SafeAreaLayout:MonoBehaviour
    {
        private Rect lastSafe;private Vector2Int lastScreen;
        private void Update(){if(lastSafe==Screen.safeArea&&lastScreen.x==Screen.width&&lastScreen.y==Screen.height)return;lastSafe=Screen.safeArea;lastScreen=new Vector2Int(Screen.width,Screen.height);var rt=(RectTransform)transform;rt.anchorMin=new Vector2(lastSafe.xMin/Screen.width,lastSafe.yMin/Screen.height);rt.anchorMax=new Vector2(lastSafe.xMax/Screen.width,lastSafe.yMax/Screen.height);rt.offsetMin=rt.offsetMax=Vector2.zero;}
    }

    [ExecuteAlways]
    public sealed class UiLayoutBounds:MonoBehaviour
    {
        public enum Kind{Text,Description,Button}
        public Kind kind;public bool visible;private Image overlay;
        private void Update(){if(overlay==null){overlay=GetComponent<Image>();if(overlay==null)overlay=gameObject.AddComponent<Image>();overlay.raycastTarget=false;}overlay.enabled=visible;overlay.color=kind==Kind.Button?new Color(1,.72f,.12f,.10f):kind==Kind.Description?new Color(.25f,1,.35f,.10f):new Color(.12f,.78f,1,.10f);}
    }

    public sealed class UiScreenShard:MaskableGraphic
    {
        public Texture source;public Rect uvRect;public bool flip;public override Texture mainTexture=>source!=null?source:Texture2D.whiteTexture;
        protected override void OnPopulateMesh(VertexHelper vh){vh.Clear();Rect r=rectTransform.rect;Vector2 bl=new Vector2(r.xMin,r.yMin),br=new Vector2(r.xMax,r.yMin),tl=new Vector2(r.xMin,r.yMax),tr=new Vector2(r.xMax,r.yMax);Vector2 uvBl=new Vector2(uvRect.xMin,uvRect.yMin),uvBr=new Vector2(uvRect.xMax,uvRect.yMin),uvTl=new Vector2(uvRect.xMin,uvRect.yMax),uvTr=new Vector2(uvRect.xMax,uvRect.yMax);Color32 c=color;if(!flip){vh.AddVert(bl,c,uvBl);vh.AddVert(br,c,uvBr);vh.AddVert(tl,c,uvTl);}else{vh.AddVert(tr,c,uvTr);vh.AddVert(tl,c,uvTl);vh.AddVert(br,c,uvBr);}vh.AddTriangle(0,1,2);}
    }

    public sealed class UiPolygonShard:MaskableGraphic
    {
        public Texture source;public Vector2[] points,uvs;public override Texture mainTexture=>source!=null?source:Texture2D.whiteTexture;
        protected override void OnPopulateMesh(VertexHelper vh){vh.Clear();if(points==null||uvs==null||points.Length<3||uvs.Length<3)return;Color32 c=color;for(int i=0;i<3;i++)vh.AddVert(points[i],c,uvs[i]);vh.AddTriangle(0,1,2);}
    }
}
