param(
    [ValidateSet('prepare','submit','status')][string]$Action = 'prepare',
    [ValidateSet('scenario','pixellab','manual')][string]$Provider = 'manual',
    [string]$Spec,
    [string]$Endpoint,
    [string]$JobId,
    [switch]$Execute
)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

function Read-Spec([string]$path) {
    if (-not $path) { throw '-Spec is required.' }
    return Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
}
function Get-EntityFolder($entity) {
    $kind = if ($entity.entityType -eq 'boss') { 'Bosses' } else { 'Enemies' }
    return Join-Path $root ("art\entities\$kind\" + $entity.id)
}
function Save-Json([string]$path, $value) {
    [System.IO.File]::WriteAllText($path,($value | ConvertTo-Json -Depth 12),(New-Object System.Text.UTF8Encoding($false)))
}
function Build-Prompt($entity) {
    $animations = ($entity.animations | ForEach-Object { "$($_.id): $($_.frames) frames at $($_.fps) FPS" }) -join '; '
    return @"
Production-ready 2.5D mobile survivors-like game sprite of $($entity.displayName), $($entity.description).
Urban fantasy and restrained near-future cyberpunk. Semi-realistic hand-painted character, clean readable silhouette, compact proportions, crisp material separation, medium contrast. Isometric three-quarter top-down camera, approximately 35 degrees downward, orthographic look, character centered, full body visible, consistent scale and ground contact. Neutral cool night key light from upper left with subtle warm industrial rim light. Transparent background, no floor, no cast shadow outside the character, no text, no UI, no border, no scenery, no extra characters, no cropped body parts.
Generate $($entity.directions) consistent directions in clockwise order: south, southwest, west, northwest, north, northeast, east, southeast. Preserve costume, anatomy, palette, equipment and proportions across every direction and frame. Animation set: $animations. Each frame must fit a square cell with at least 8 percent transparent padding. Direction rows, animation-frame columns. Avoid photorealism, chibi proportions, pixel art, excessive particles, motion blur and baked background.
Unique visual notes: $($entity.visualNotes)
Gameplay readability: $($entity.gameplayReadability)
"@
}

if ($Action -eq 'prepare') {
    $entity = Read-Spec $Spec
    if (@('hero_amelia','hero_sam','hero_zike') -contains $entity.id) { throw 'Existing heroes are protected and may not be regenerated by this workflow.' }
    $folder = Get-EntityFolder $entity
    $source = Join-Path $folder 'Source'
    New-Item -ItemType Directory -Path $source -Force | Out-Null
    Copy-Item -LiteralPath $Spec -Destination (Join-Path $folder 'entity.json') -Force
    $prompt = Build-Prompt $entity
    [System.IO.File]::WriteAllText((Join-Path $folder 'generation-prompt.txt'),$prompt,(New-Object System.Text.UTF8Encoding($false)))
    $scenario = [ordered]@{ prompt=$prompt; negativePrompt='background, scenery, text, UI, watermark, cropped feet, inconsistent costume, duplicate limbs, photorealistic, pixel art, excessive particles, motion blur'; width=1024; height=1024; numSamples=1 }
    $pixellab = [ordered]@{ description=$prompt; image_size=[ordered]@{width=256;height=256}; directions=$entity.directions; no_background=$true; view='low top-down'; proportions='adult heroic'; animations=$entity.animations }
    Save-Json (Join-Path $folder 'scenario-request.json') $scenario
    Save-Json (Join-Path $folder 'pixellab-request.json') $pixellab
    Write-Host "Prepared $($entity.id) in $folder"
    Write-Host "Place exported sheets in $source using: <entity>__<animation>__<1|4|8>dir__<fps>fps__<loop|once>.png"
    exit 0
}

if (-not $Execute) { throw 'External requests are disabled by default. Re-run with -Execute after reviewing the generated request and provider credit cost.' }
if ($Action -eq 'submit') {
    $entity = Read-Spec $Spec
    $folder = Get-EntityFolder $entity
    if ($Provider -eq 'scenario') {
        if (-not $env:SCENARIO_API_KEY -or -not $env:SCENARIO_API_SECRET -or -not $env:SCENARIO_MODEL_ID) { throw 'Set SCENARIO_API_KEY, SCENARIO_API_SECRET and SCENARIO_MODEL_ID.' }
        $uri = "https://api.cloud.scenario.com/v1/generate/custom/$($env:SCENARIO_MODEL_ID)"
        $token = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($env:SCENARIO_API_KEY):$($env:SCENARIO_API_SECRET)"))
        $headers = @{ Authorization="Basic $token"; Accept='application/json' }
        $body = Get-Content -LiteralPath (Join-Path $folder 'scenario-request.json') -Raw
    } elseif ($Provider -eq 'pixellab') {
        if (-not $env:PIXELLAB_API_TOKEN) { throw 'Set PIXELLAB_API_TOKEN.' }
        if (-not $Endpoint) { $Endpoint='/create-character-with-8-directions' }
        $uri = 'https://api.pixellab.ai/v2' + $Endpoint
        $headers = @{ Authorization="Bearer $($env:PIXELLAB_API_TOKEN)"; Accept='application/json' }
        $body = Get-Content -LiteralPath (Join-Path $folder 'pixellab-request.json') -Raw
    } else { throw 'Manual provider cannot submit.' }
    $response = Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -ContentType 'application/json' -Body $body
    New-Item -ItemType Directory -Path (Join-Path $root 'art\.local') -Force | Out-Null
    Save-Json (Join-Path $root "art\.local\$($Provider)-submit-$($entity.id).json") $response
    $response | ConvertTo-Json -Depth 12
    exit 0
}

if ($Action -eq 'status') {
    if (-not $JobId) { throw '-JobId is required.' }
    if ($Provider -eq 'scenario') {
        if (-not $env:SCENARIO_API_KEY -or -not $env:SCENARIO_API_SECRET) { throw 'Set SCENARIO_API_KEY and SCENARIO_API_SECRET.' }
        $token = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($env:SCENARIO_API_KEY):$($env:SCENARIO_API_SECRET)"))
        $headers = @{ Authorization="Basic $token"; Accept='application/json' }; $uri="https://api.cloud.scenario.com/v1/jobs/$JobId"
    } elseif ($Provider -eq 'pixellab') {
        if (-not $env:PIXELLAB_API_TOKEN) { throw 'Set PIXELLAB_API_TOKEN.' }
        $headers = @{ Authorization="Bearer $($env:PIXELLAB_API_TOKEN)"; Accept='application/json' }; $uri="https://api.pixellab.ai/v2/background-jobs/$JobId"
    } else { throw 'Manual provider has no job status.' }
    Invoke-RestMethod -Method Get -Uri $uri -Headers $headers | ConvertTo-Json -Depth 12
}
